-- MySQL Script generated by MySQL Workbench
-- Thu 17 Oct 2024 03:35:32 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COURSE` (
  `Number` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Credits` VARCHAR(45) NULL,
  `Syllabus` VARCHAR(45) NULL,
  `Pre-Requisite` VARCHAR(45) NULL,
  PRIMARY KEY (`Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INSTRUCTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSTRUCTOR` (
  `IDNo` INT NOT NULL,
  `Department` VARCHAR(45) NULL,
  `Title` VARCHAR(45) NULL,
  PRIMARY KEY (`IDNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COURSE OFFERING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COURSE OFFERING` (
  `Number` INT NOT NULL,
  `COURSE` VARCHAR(45) NULL,
  `Year` YEAR NULL,
  `Semester` INT NULL,
  `Section No` INT NULL,
  `Instructor` INT NULL DEFAULT '',
  `Timing` VARCHAR(45) NULL,
  `Classroom` INT NULL,
  PRIMARY KEY (`Number`),
  UNIQUE INDEX `Number_UNIQUE` (`Number` ASC) VISIBLE,
  UNIQUE INDEX `COURSE_UNIQUE` (`COURSE` ASC) VISIBLE,
  INDEX `IDNo_idx` (`Instructor` ASC) VISIBLE,
  CONSTRAINT `Number`
    FOREIGN KEY (`Number`)
    REFERENCES `mydb`.`COURSE` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDNo`
    FOREIGN KEY (`Instructor`)
    REFERENCES `mydb`.`INSTRUCTOR` (`IDNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STUDENT` (
  `StudentID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Program` VARCHAR(45) NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
